In [2]:
import zipfile

zip_path = "memotion_dataset.zip"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall("dataset")

print("Extracted successfully ✅")

Extracted successfully ✅

In [3]:
import os

os.listdir("dataset/memotion_dataset_7k")

['images',
 'labels.csv',
 'labels.xlsx',
 'labels_pd_pickle',
 'reference.csv',
 'reference.xlsx',
 'reference_df_pickle']

In [4]:
import pandas as pd

df = pd.read_csv("dataset/memotion_dataset_7k/labels.csv")

# take small data (VERY IMPORTANT ⚡)
df = df.sample(150, random_state=42)

df.head()

,Unnamed: 0,image_name,text_ocr,text_corrected,humour,sarcasm,offensive,motivational,overall_sentiment
4498,4498,image_4499.jpg,I once had a Lizard and a Fish as pets..,I once had a Lizard and a Fish as pets..,funny,twisted_meaning,slight,not_motivational,positive
3936,3936,image_3937.jpeg,GOES TO SCHOOL WITH 15 POGS COMES HOME WITH 100,GOES TO SCHOOL WITH 15 POGS COMES HOME WITH 100,very_funny,general,very_offensive,motivational,negative
5059,5059,image_5060.jpg,MERICA wo FRENCH FRY HOLDER FUCK YEAH imgflip.com,MERICA FRENCH FRY HOLDER FUCK YEAH imgflip.com,funny,general,not_offensive,not_motivational,positive
1379,1379,image_1380.jpg,3x02 GAANOTHSCENES You know what's weird. Dona...,3x02 GAANOTHSCENES You know what's weird. Dona...,funny,very_twisted,slight,not_motivational,positive
3870,3870,image_3871.png,@NFL_MEMES EACH SPORT HAS IT'S GREATEST BUT HE...,@NFL_MEMES EACH SPORT HAS IT'S GREATEST BUT HE...,not_funny,not_sarcastic,not_offensive,motivational,neutral

In [5]:
df.columns

Index(['Unnamed: 0', 'image_name', 'text_ocr', 'text_corrected', 'humour',
       'sarcasm', 'offensive', 'motivational', 'overall_sentiment'],
      dtype='object')

In [6]:
df = pd.read_csv("dataset/memotion_dataset_7k/labels.csv")

# drop useless column
df = df.drop(columns=["Unnamed: 0"])

# take small data (IMPORTANT ⚡)
df = df.sample(150, random_state=42)

df.head()

,image_name,text_ocr,text_corrected,humour,sarcasm,offensive,motivational,overall_sentiment
4498,image_4499.jpg,I once had a Lizard and a Fish as pets..,I once had a Lizard and a Fish as pets..,funny,twisted_meaning,slight,not_motivational,positive
3936,image_3937.jpeg,GOES TO SCHOOL WITH 15 POGS COMES HOME WITH 100,GOES TO SCHOOL WITH 15 POGS COMES HOME WITH 100,very_funny,general,very_offensive,motivational,negative
5059,image_5060.jpg,MERICA wo FRENCH FRY HOLDER FUCK YEAH imgflip.com,MERICA FRENCH FRY HOLDER FUCK YEAH imgflip.com,funny,general,not_offensive,not_motivational,positive
1379,image_1380.jpg,3x02 GAANOTHSCENES You know what's weird. Dona...,3x02 GAANOTHSCENES You know what's weird. Dona...,funny,very_twisted,slight,not_motivational,positive
3870,image_3871.png,@NFL_MEMES EACH SPORT HAS IT'S GREATEST BUT HE...,@NFL_MEMES EACH SPORT HAS IT'S GREATEST BUT HE...,not_funny,not_sarcastic,not_offensive,motivational,neutral

In [7]:
df['text'] = df['text_corrected'].fillna("")

In [8]:
!pip install transformers torch torchvision

Requirement already satisfied: transformers in c:\users\palak bhardwaj\anaconda3\lib\site-packages (5.7.0)
Requirement already satisfied: torch in c:\users\palak bhardwaj\anaconda3\lib\site-packages (2.10.0)
Requirement already satisfied: torchvision in c:\users\palak bhardwaj\anaconda3\lib\site-packages (0.25.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (1.13.0)
Requirement already satisfied: numpy>=1.17 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (2.1.3)
Requirement already satisfied: packaging>=20.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (6.0.2)
Requirement already satisfied: regex>=2025.10.22 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (2026.4.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (0.9.0)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (4.67.1)
Requirement already satisfied: filelock>=3.10.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.17.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2025.3.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.12.2)
Requirement already satisfied: anyio in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.7.0)
Requirement already satisfied: certifi in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2025.4.26)
Requirement already satisfied: httpcore==1.* in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.7)
Requirement already satisfied: h11>=0.16 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from torch) (1.13.3)
Requirement already satisfied: networkx>=2.5.1 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from torch) (3.4.2)
Requirement already satisfied: jinja2 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from torch) (3.1.6)
Requirement already satisfied: setuptools in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from torch) (72.1.0)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from torchvision) (11.1.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: colorama in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from tqdm>=4.27->transformers) (0.4.6)
Requirement already satisfied: sniffio>=1.1 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from jinja2->torch) (3.0.2)
Requirement already satisfied: click<9.0.0,>=7.1.1 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from typer->transformers) (8.1.8)

In [9]:
from transformers import pipeline

sentiment_model = pipeline(
    "sentiment-analysis",
    model="distilbert-base-uncased-finetuned-sst-2-english"
)

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

In [12]:
!pip install transformers torch torchvision pillow

Requirement already satisfied: transformers in c:\users\palak bhardwaj\anaconda3\lib\site-packages (5.7.0)
Requirement already satisfied: torch in c:\users\palak bhardwaj\anaconda3\lib\site-packages (2.10.0)
Requirement already satisfied: torchvision in c:\users\palak bhardwaj\anaconda3\lib\site-packages (0.25.0)
Requirement already satisfied: pillow in c:\users\palak bhardwaj\anaconda3\lib\site-packages (11.1.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (1.13.0)
Requirement already satisfied: numpy>=1.17 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (2.1.3)
Requirement already satisfied: packaging>=20.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (6.0.2)
Requirement already satisfied: regex>=2025.10.22 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (2026.4.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (0.9.0)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (4.67.1)
Requirement already satisfied: filelock>=3.10.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.17.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2025.3.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.12.2)
Requirement already satisfied: anyio in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.7.0)
Requirement already satisfied: certifi in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2025.4.26)
Requirement already satisfied: httpcore==1.* in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.7)
Requirement already satisfied: h11>=0.16 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from torch) (1.13.3)
Requirement already satisfied: networkx>=2.5.1 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from torch) (3.4.2)
Requirement already satisfied: jinja2 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from torch) (3.1.6)
Requirement already satisfied: setuptools in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from torch) (72.1.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: colorama in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from tqdm>=4.27->transformers) (0.4.6)
Requirement already satisfied: sniffio>=1.1 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from jinja2->torch) (3.0.2)
Requirement already satisfied: click<9.0.0,>=7.1.1 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from typer->transformers) (8.1.8)

In [11]:
from transformers import CLIPProcessor, CLIPModel
import torch

model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")
processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")

config.json: 0.00B [00:00, ?B/s]

C:\Users\Palak Bhardwaj\anaconda3\Lib\site-packages\huggingface_hub\file_download.py:138: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Palak Bhardwaj\.cache\huggingface\hub\models--openai--clip-vit-base-patch32. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

pytorch_model.bin:   0%|          | 0.00/605M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/398 [00:00<?, ?it/s]

model.safetensors:   0%|          | 0.00/605M [00:00<?, ?B/s]

preprocessor_config.json:   0%|          | 0.00/316 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/592 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/389 [00:00<?, ?B/s]

In [13]:
!pip install transformers torch pillow pandas

Requirement already satisfied: transformers in c:\users\palak bhardwaj\anaconda3\lib\site-packages (5.7.0)
Requirement already satisfied: torch in c:\users\palak bhardwaj\anaconda3\lib\site-packages (2.10.0)
Requirement already satisfied: pillow in c:\users\palak bhardwaj\anaconda3\lib\site-packages (11.1.0)
Requirement already satisfied: pandas in c:\users\palak bhardwaj\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (1.13.0)
Requirement already satisfied: numpy>=1.17 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (2.1.3)
Requirement already satisfied: packaging>=20.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (6.0.2)
Requirement already satisfied: regex>=2025.10.22 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (2026.4.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (0.9.0)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (4.67.1)
Requirement already satisfied: filelock>=3.10.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.17.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2025.3.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.12.2)
Requirement already satisfied: anyio in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.7.0)
Requirement already satisfied: certifi in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2025.4.26)
Requirement already satisfied: httpcore==1.* in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.7)
Requirement already satisfied: h11>=0.16 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from torch) (1.13.3)
Requirement already satisfied: networkx>=2.5.1 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from torch) (3.4.2)
Requirement already satisfied: jinja2 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from torch) (3.1.6)
Requirement already satisfied: setuptools in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from torch) (72.1.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: colorama in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from tqdm>=4.27->transformers) (0.4.6)
Requirement already satisfied: sniffio>=1.1 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from jinja2->torch) (3.0.2)
Requirement already satisfied: click<9.0.0,>=7.1.1 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from typer->transformers) (8.1.8)

In [14]:
import pandas as pd
import torch
from transformers import CLIPProcessor, CLIPModel
from PIL import Image
import os

In [15]:
df = pd.read_csv("dataset/memotion_dataset_7k/labels.csv")

# clean
df = df.drop(columns=["Unnamed: 0"])

# small subset (important for laptop)
df = df.sample(100, random_state=42).reset_index(drop=True)

# use clean text
df['text'] = df['text_corrected'].fillna("")

In [16]:
model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")
processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")

Loading weights:   0%|          | 0/398 [00:00<?, ?it/s]

In [37]:
labels = ["positive meme", "negative meme"]

In [38]:
def predict_multimodal(row):
    try:
        image_path = os.path.join(
            "dataset/memotion_dataset_7k/images",
            row['image_name']
        )
        
        text = row['text']
        image = Image.open(image_path).convert("RGB")
        
        inputs = processor(
            text=[text + " " + l for l in labels],
            images=image,
            return_tensors="pt",
            padding=True
        )
        
        outputs = model(**inputs)
        probs = outputs.logits_per_image.softmax(dim=1)
        
        idx = torch.argmax(probs).item()
        
        label = "positive" if idx == 0 else "negative"
        score = probs[0][idx].item()
        
        return label, score
    
    except:
        return "error", 0.0

In [39]:
results = []

for _, row in df.iterrows():
    pred, score = predict_multimodal(row)
    
    results.append({
        "image": row['image_name'],
        "predicted": pred,
        "confidence": score,
        "actual": row['overall_sentiment']
    })

result_df = pd.DataFrame(results)
result_df.head()

             image predicted  confidence    actual
0   image_4499.jpg  positive    0.794922  positive
1  image_3937.jpeg  negative    0.670775  negative
2   image_5060.jpg  negative    0.538206  positive
3   image_1380.jpg  negative    0.546658  positive
4   image_3871.png  positive    0.574390   neutral

In [40]:
def explain(row):
    text = row['text']
    pred = row['predicted']
    
    humour = row['humour']
    sarcasm = row['sarcasm']
    offensive = row['offensive']
    
    explanation = f"Meme: '{text[:40]}'. "
    
    if pred == "positive":
        explanation += "Positive because "
        
        reasons = []
        
        if humour in ["funny", "very_funny", "hilarious"]:
            reasons.append("it is humorous")
        if sarcasm == "not_sarcastic":
            reasons.append("it has no sarcasm")
        if offensive == "not_offensive":
            reasons.append("it is not offensive")
        
        if not reasons:
            reasons.append("the tone is pleasant")
        
        explanation += ", ".join(reasons) + "."
    
    elif pred == "negative":
        explanation += "Negative because "
        
        reasons = []
        
        if sarcasm != "not_sarcastic":
            reasons.append("it contains sarcasm")
        if offensive != "not_offensive":
            reasons.append("it may be offensive")
        if humour == "not_funny":
            reasons.append("it lacks humor")
        
        if not reasons:
            reasons.append("the tone is negative")
        
        explanation += ", ".join(reasons) + "."
    
    return explanation

In [41]:
df["predicted"] = result_df["predicted"]

df["explanation"] = df.apply(explain, axis=1)

df[["image_name", "predicted", "explanation"]].head()

,image_name,predicted,explanation
0,image_4499.jpg,positive,Meme: 'I once had a Lizard and a Fish as pets....
1,image_3937.jpeg,negative,Meme: 'GOES TO SCHOOL WITH 15 POGS COMES HOME ...
2,image_5060.jpg,negative,Meme: 'MERICA FRENCH FRY HOLDER FUCK YEAH imgf...
3,image_1380.jpg,negative,Meme: '3x02 GAANOTHSCENES You know what's weir...
4,image_3871.png,positive,Meme: '@NFL_MEMES EACH SPORT HAS IT'S GREATEST...

In [42]:
print(explain(df.iloc[0]))

Meme: 'I once had a Lizard and a Fish as pets..'. Positive because it is humorous.

In [43]:
df_30 = df.head(30)

df_30["explanation"] = df_30.apply(explain, axis=1)

df_30[["image_name", "predicted", "explanation"]]

C:\Users\Palak Bhardwaj\AppData\Local\Temp\ipykernel_7072\1468168292.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_30["explanation"] = df_30.apply(explain, axis=1)

,image_name,predicted,explanation
0,image_4499.jpg,positive,Meme: 'I once had a Lizard and a Fish as pets....
1,image_3937.jpeg,negative,Meme: 'GOES TO SCHOOL WITH 15 POGS COMES HOME ...
2,image_5060.jpg,negative,Meme: 'MERICA FRENCH FRY HOLDER FUCK YEAH imgf...
3,image_1380.jpg,negative,Meme: '3x02 GAANOTHSCENES You know what's weir...
4,image_3871.png,positive,Meme: '@NFL_MEMES EACH SPORT HAS IT'S GREATEST...
5,image_2119.png,negative,Meme: 'MY TEACHER ALWAYS SAID THAT IF YOU POIN...
6,image_1080.jpg,negative,Meme: 'CASH ME OUTSIDE HOW BOUT NO'. Negative ...
7,image_1562.jpg,positive,"Meme: 'DO YOU KNOW WHAT THE T STANDS FOR IN ""M..."
8,image_3892.jpg,positive,Meme: 'THIS APPLE IS SO RAW THAT STEVE JOBS WA...
9,image_2756.jpg,positive,Meme: 'WHEN YOU FINISH AN EXAM FIRST AND WONDE...
10,image_997.jpg,positive,Meme: 'RARE PICTURE OF LEONARDO DICAPRIO HOLDI...
11,image_3384.jpg,negative,Meme: 'You can't be racist if there is no othe...
12,image_5049.png,positive,Meme: 'memes about self hatred memes about lov...
13,image_6443.jpg,negative,Meme: 'HAPPY FRIDAY! WAIT SORRY IT'S MONDAY'...
14,image_3943.jpg,negative,Meme: '47 SUCCESS KID MEMES THAT SHOW EVEN THE...
15,image_1421.jpg,negative,Meme: 'Here is a rare photo of a middle Americ...
16,image_5091.jpg,positive,Meme: 'W AND I SAID UNTO THEM DONT MAKE THE SU...
17,image_6639.png,positive,Meme: 'TAM NOT ANTI RELIGION. TAM ANTI SEXISM ...
18,image_2178.jpg,negative,"Meme: 'Jim Carrey ""America is morally upside d..."
19,image_1596.png,positive,Meme: 'GIORGIO ARMANI THE VULP OF ALL STREP TH...
20,image_3313.jpg,negative,Meme: 'THIS WILL TEACH YOU NOT TO MAKE MEMES'....
21,image_2986.jpg,positive,Meme: 'AND THEN I TOLD THEM I'D FIX THE ECONOM...
22,image_4005.png,positive,"Meme: 'Crypto ""Experts"": *Choose crypto invest..."
23,image_6392.jpeg,negative,Meme: 'The broken hearts of Westeros'. Negativ...
24,image_6181.jpg,negative,Meme: 'My cat was missing for several hours un...
25,image_6497.png,negative,"Meme: 'Jim Carrey calls Brett Kavanaugh ""an en..."
26,image_6149.png,positive,Meme: 'This is Bill. Bill is on Facebook. Bill...
27,image_6705.png,negative,Meme: 'A fight breaks out when a husband comes...
28,image_6101.png,positive,Meme: 'I'm such a mess. Why do you even like m...
29,image_5024.jpg,negative,Meme: 'KNOWS ARAGORN IS SOULMATES WITH ARWEN K...

In [44]:
for i in range(30):
    print(f"Image: {df.iloc[i]['image_name']}")
    print(f"Prediction: {df.iloc[i]['predicted']}")
    print(explain(df.iloc[i]))
    print("-"*50)

Image: image_4499.jpg
Prediction: positive
Meme: 'I once had a Lizard and a Fish as pets..'. Positive because it is humorous.
--------------------------------------------------
Image: image_3937.jpeg
Prediction: negative
Meme: 'GOES TO SCHOOL WITH 15 POGS COMES HOME W'. Negative because it contains sarcasm, it may be offensive.
--------------------------------------------------
Image: image_5060.jpg
Prediction: negative
Meme: 'MERICA FRENCH FRY HOLDER FUCK YEAH imgfl'. Negative because it contains sarcasm.
--------------------------------------------------
Image: image_1380.jpg
Prediction: negative
Meme: '3x02 GAANOTHSCENES You know what's weird'. Negative because it contains sarcasm, it may be offensive.
--------------------------------------------------
Image: image_3871.png
Prediction: positive
Meme: '@NFL_MEMES EACH SPORT HAS IT'S GREATEST '. Positive because it has no sarcasm, it is not offensive.
--------------------------------------------------
Image: image_2119.png
Prediction: negative
Meme: 'MY TEACHER ALWAYS SAID THAT IF YOU POINT'. Negative because it contains sarcasm.
--------------------------------------------------
Image: image_1080.jpg
Prediction: negative
Meme: 'CASH ME OUTSIDE HOW BOUT NO'. Negative because the tone is negative.
--------------------------------------------------
Image: image_1562.jpg
Prediction: positive
Meme: 'DO YOU KNOW WHAT THE T STANDS FOR IN "MO'. Positive because it is humorous, it is not offensive.
--------------------------------------------------
Image: image_3892.jpg
Prediction: positive
Meme: 'THIS APPLE IS SO RAW THAT STEVE JOBS WAS'. Positive because it is humorous.
--------------------------------------------------
Image: image_2756.jpg
Prediction: positive
Meme: 'WHEN YOU FINISH AN EXAM FIRST AND WONDER'. Positive because it is humorous.
--------------------------------------------------
Image: image_997.jpg
Prediction: positive
Meme: 'RARE PICTURE OF LEONARDO DICAPRIO HOLDIN'. Positive because it is humorous, it has no sarcasm, it is not offensive.
--------------------------------------------------
Image: image_3384.jpg
Prediction: negative
Meme: 'You can't be racist if there is no other'. Negative because it contains sarcasm, it may be offensive.
--------------------------------------------------
Image: image_5049.png
Prediction: positive
Meme: 'memes about self hatred memes about lovi'. Positive because it is humorous.
--------------------------------------------------
Image: image_6443.jpg
Prediction: negative
Meme: 'HAPPY FRIDAY! WAIT  SORRY  IT'S MONDAY'. Negative because it contains sarcasm, it may be offensive.
--------------------------------------------------
Image: image_3943.jpg
Prediction: negative
Meme: '47 SUCCESS KID MEMES THAT SHOW EVEN THE '. Negative because it may be offensive.
--------------------------------------------------
Image: image_1421.jpg
Prediction: negative
Meme: 'Here is a rare photo of a middle America'. Negative because it lacks humor.
--------------------------------------------------
Image: image_5091.jpg
Prediction: positive
Meme: 'W AND I SAID UNTO THEM DONT MAKE THE SUP'. Positive because it is humorous, it is not offensive.
--------------------------------------------------
Image: image_6639.png
Prediction: positive
Meme: 'TAM NOT ANTI RELIGION. TAM ANTI SEXISM A'. Positive because the tone is pleasant.
--------------------------------------------------
Image: image_2178.jpg
Prediction: negative
Meme: 'Jim Carrey "America is morally upside do'. Negative because it contains sarcasm, it lacks humor.
--------------------------------------------------
Image: image_1596.png
Prediction: positive
Meme: 'GIORGIO ARMANI THE VULP OF ALL STREP THE'. Positive because it is humorous, it has no sarcasm, it is not offensive.
--------------------------------------------------
Image: image_3313.jpg
Prediction: negative
Meme: 'THIS WILL TEACH YOU NOT TO MAKE MEMES'. Negative because it contains sarcasm, it lacks humor.
--------------------------------------------------
Image: image_2986.jpg
Prediction: positive
Meme: 'AND THEN I TOLD THEM I'D FIX THE ECONOMY'. Positive because it is humorous, it is not offensive.
--------------------------------------------------
Image: image_4005.png
Prediction: positive
Meme: 'Crypto "Experts": *Choose crypto investm'. Positive because it is humorous, it is not offensive.
--------------------------------------------------
Image: image_6392.jpeg
Prediction: negative
Meme: 'The broken hearts of Westeros'. Negative because it contains sarcasm, it may be offensive.
--------------------------------------------------
Image: image_6181.jpg
Prediction: negative
Meme: 'My cat was missing for several hours unt'. Negative because it contains sarcasm.
--------------------------------------------------
Image: image_6497.png
Prediction: negative
Meme: 'Jim Carrey calls Brett Kavanaugh "an ent'. Negative because it contains sarcasm, it may be offensive.
--------------------------------------------------
Image: image_6149.png
Prediction: positive
Meme: 'This is Bill. Bill is on Facebook. Bill '. Positive because it is humorous.
--------------------------------------------------
Image: image_6705.png
Prediction: negative
Meme: 'A fight breaks out when a husband comes '. Negative because the tone is negative.
--------------------------------------------------
Image: image_6101.png
Prediction: positive
Meme: 'I'm such a mess. Why do you even like me'. Positive because it is humorous.
--------------------------------------------------
Image: image_5024.jpg
Prediction: negative
Meme: 'KNOWS ARAGORN IS SOULMATES WITH ARWEN KE'. Negative because it contains sarcasm, it may be offensive.
--------------------------------------------------

In [45]:
!pip install transformers accelerate

Requirement already satisfied: transformers in c:\users\palak bhardwaj\anaconda3\lib\site-packages (5.7.0)
Requirement already satisfied: accelerate in c:\users\palak bhardwaj\anaconda3\lib\site-packages (1.13.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (1.13.0)
Requirement already satisfied: numpy>=1.17 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (2.1.3)
Requirement already satisfied: packaging>=20.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (6.0.2)
Requirement already satisfied: regex>=2025.10.22 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (2026.4.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (0.9.0)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (4.67.1)
Requirement already satisfied: filelock>=3.10.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.17.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2025.3.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.12.2)
Requirement already satisfied: anyio in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.7.0)
Requirement already satisfied: certifi in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2025.4.26)
Requirement already satisfied: httpcore==1.* in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.7)
Requirement already satisfied: h11>=0.16 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: psutil in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from accelerate) (5.9.0)
Requirement already satisfied: torch>=2.0.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from accelerate) (2.10.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from torch>=2.0.0->accelerate) (1.13.3)
Requirement already satisfied: networkx>=2.5.1 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from torch>=2.0.0->accelerate) (3.4.2)
Requirement already satisfied: jinja2 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: setuptools in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from torch>=2.0.0->accelerate) (72.1.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: colorama in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from tqdm>=4.27->transformers) (0.4.6)
Requirement already satisfied: sniffio>=1.1 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.2)
Requirement already satisfied: click<9.0.0,>=7.1.1 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from typer->transformers) (8.1.8)

In [5]:
!pip install --upgrade transformers

Collecting transformers
  Using cached transformers-5.7.0-py3-none-any.whl.metadata (33 kB)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (1.13.0)
Requirement already satisfied: numpy>=1.17 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (2.1.3)
Requirement already satisfied: packaging>=20.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (6.0.2)
Requirement already satisfied: regex>=2025.10.22 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (2026.4.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (0.9.0)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (4.67.1)
Requirement already satisfied: filelock>=3.10.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.17.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2025.3.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.12.2)
Requirement already satisfied: anyio in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.7.0)
Requirement already satisfied: certifi in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2025.4.26)
Requirement already satisfied: httpcore==1.* in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.7)
Requirement already satisfied: h11>=0.16 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: colorama in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from tqdm>=4.27->transformers) (0.4.6)
Requirement already satisfied: sniffio>=1.1 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.3.0)
Requirement already satisfied: click<9.0.0,>=7.1.1 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from typer->transformers) (8.1.8)
Using cached transformers-5.7.0-py3-none-any.whl (10.5 MB)
Installing collected packages: transformers
Successfully installed transformers-5.7.0

In [8]:
!pip install transformers torch pandas

Collecting transformers
  Using cached transformers-5.7.0-py3-none-any.whl.metadata (33 kB)
Requirement already satisfied: torch in c:\users\palak bhardwaj\anaconda3\lib\site-packages (2.10.0)
Requirement already satisfied: pandas in c:\users\palak bhardwaj\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (1.13.0)
Requirement already satisfied: numpy>=1.17 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (2.1.3)
Requirement already satisfied: packaging>=20.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (6.0.2)
Requirement already satisfied: regex>=2025.10.22 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (2026.4.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (0.9.0)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (4.67.1)
Requirement already satisfied: filelock>=3.10.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.17.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2025.3.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.12.2)
Requirement already satisfied: anyio in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.7.0)
Requirement already satisfied: certifi in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2025.4.26)
Requirement already satisfied: httpcore==1.* in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.7)
Requirement already satisfied: h11>=0.16 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from torch) (1.13.3)
Requirement already satisfied: networkx>=2.5.1 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from torch) (3.4.2)
Requirement already satisfied: jinja2 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from torch) (3.1.6)
Requirement already satisfied: setuptools in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from torch) (72.1.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: colorama in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from tqdm>=4.27->transformers) (0.4.6)
Requirement already satisfied: sniffio>=1.1 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from jinja2->torch) (3.0.2)
Requirement already satisfied: click<9.0.0,>=7.1.1 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from typer->transformers) (8.1.8)
Using cached transformers-5.7.0-py3-none-any.whl (10.5 MB)
Installing collected packages: transformers
Successfully installed transformers-5.7.0

In [9]:
import pandas as pd

df = pd.read_csv("dataset/memotion_dataset_7k/labels.csv")

df = df.drop(columns=["Unnamed: 0"])

# small subset
df = df.sample(100, random_state=42).reset_index(drop=True)

df['text'] = df['text_corrected'].fillna("")

In [10]:
from transformers import pipeline

sentiment_model = pipeline(
    "sentiment-analysis",
    model="distilbert-base-uncased-finetuned-sst-2-english"
)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

In [11]:
def predict_sentiment(text):
    result = sentiment_model(text[:512])[0]
    
    label = "positive" if result['label'] == "POSITIVE" else "negative"
    score = result['score']
    
    return label, score

In [12]:
results = []

for _, row in df.iterrows():
    label, score = predict_sentiment(row['text'])
    
    results.append({
        "predicted": label,
        "confidence": score
    })

result_df = pd.DataFrame(results)

df["predicted"] = result_df["predicted"]

In [13]:
def explain(row):
    text = str(row['text'])
    pred = row['predicted']
    
    humour = str(row['humour']).lower()
    sarcasm = str(row['sarcasm']).lower()
    offensive = str(row['offensive']).lower()
    
    explanation = f"This meme is {pred} because "
    
    reasons = []
    
    if pred == "positive":
        if "funny" in humour or "hilarious" in humour:
            reasons.append("it contains humor")
        if "not" in sarcasm:
            reasons.append("it is not sarcastic")
        if "not" in offensive:
            reasons.append("it is not offensive")
    
    else:
        if "sarcasm" in sarcasm or "twisted" in sarcasm:
            reasons.append("it contains sarcasm")
        if "offensive" in offensive and "not" not in offensive:
            reasons.append("it may be offensive")
        if "not_funny" in humour:
            reasons.append("it lacks humor")
    
    if not reasons:
        reasons.append("the overall tone of the text suggests this sentiment")
    
    explanation += ", ".join(reasons) + "."
    
    return explanation

In [14]:
df_30 = df.head(30)

df_30["explanation"] = df_30.apply(explain, axis=1)

df_30[["image_name", "predicted", "explanation"]]

C:\Users\Palak Bhardwaj\AppData\Local\Temp\ipykernel_856\1468168292.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_30["explanation"] = df_30.apply(explain, axis=1)

,image_name,predicted,explanation
0,image_4499.jpg,negative,This meme is negative because it contains sarc...
1,image_3937.jpeg,positive,This meme is positive because it contains humor.
2,image_5060.jpg,negative,This meme is negative because the overall tone...
3,image_1380.jpg,negative,This meme is negative because it contains sarc...
4,image_3871.png,positive,This meme is positive because it contains humo...
5,image_2119.png,negative,This meme is negative because the overall tone...
6,image_1080.jpg,negative,This meme is negative because the overall tone...
7,image_1562.jpg,negative,This meme is negative because it contains sarc...
8,image_3892.jpg,positive,This meme is positive because it contains humor.
9,image_2756.jpg,positive,This meme is positive because it contains humor.
10,image_997.jpg,positive,This meme is positive because it contains humo...
11,image_3384.jpg,negative,This meme is negative because it contains sarc...
12,image_5049.png,positive,This meme is positive because it contains humor.
13,image_6443.jpg,negative,This meme is negative because it may be offens...
14,image_3943.jpg,negative,This meme is negative because the overall tone...
15,image_1421.jpg,positive,This meme is positive because it contains humo...
16,image_5091.jpg,negative,This meme is negative because the overall tone...
17,image_6639.png,negative,This meme is negative because it contains sarc...
18,image_2178.jpg,negative,This meme is negative because it contains sarc...
19,image_1596.png,negative,This meme is negative because the overall tone...
20,image_3313.jpg,positive,This meme is positive because it contains humo...
21,image_2986.jpg,negative,This meme is negative because it contains sarc...
22,image_4005.png,positive,This meme is positive because it contains humo...
23,image_6392.jpeg,positive,This meme is positive because it contains humor.
24,image_6181.jpg,negative,This meme is negative because the overall tone...
25,image_6497.png,negative,This meme is negative because it contains sarc...
26,image_6149.png,positive,This meme is positive because it contains humor.
27,image_6705.png,negative,This meme is negative because the overall tone...
28,image_6101.png,negative,This meme is negative because the overall tone...
29,image_5024.jpg,positive,This meme is positive because it contains humor.

In [ ]:
# nowwwww

In [15]:
!pip install transformers torch pillow

Requirement already satisfied: transformers in c:\users\palak bhardwaj\anaconda3\lib\site-packages (5.7.0)
Requirement already satisfied: torch in c:\users\palak bhardwaj\anaconda3\lib\site-packages (2.10.0)
Requirement already satisfied: pillow in c:\users\palak bhardwaj\anaconda3\lib\site-packages (11.1.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (1.13.0)
Requirement already satisfied: numpy>=1.17 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (2.1.3)
Requirement already satisfied: packaging>=20.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (6.0.2)
Requirement already satisfied: regex>=2025.10.22 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (2026.4.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (0.9.0)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers) (4.67.1)
Requirement already satisfied: filelock>=3.10.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.17.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2025.3.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.12.2)
Requirement already satisfied: anyio in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.7.0)
Requirement already satisfied: certifi in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2025.4.26)
Requirement already satisfied: httpcore==1.* in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.7)
Requirement already satisfied: h11>=0.16 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from torch) (1.13.3)
Requirement already satisfied: networkx>=2.5.1 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from torch) (3.4.2)
Requirement already satisfied: jinja2 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from torch) (3.1.6)
Requirement already satisfied: setuptools in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from torch) (72.1.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: colorama in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from tqdm>=4.27->transformers) (0.4.6)
Requirement already satisfied: sniffio>=1.1 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from jinja2->torch) (3.0.2)
Requirement already satisfied: click<9.0.0,>=7.1.1 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from typer->transformers) (8.1.8)

In [16]:
from transformers import pipeline, CLIPProcessor, CLIPModel
from PIL import Image
import torch, os

# text model
text_model = pipeline("sentiment-analysis")

# image model
clip_model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")
clip_processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")

labels = ["positive meme", "negative meme"]

[transformers] No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f.
Using a pipeline without specifying a model name and revision in production is not recommended.

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

C:\Users\Palak Bhardwaj\anaconda3\Lib\site-packages\huggingface_hub\file_download.py:138: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Palak Bhardwaj\.cache\huggingface\hub\models--distilbert--distilbert-base-uncased-finetuned-sst-2-english. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

Loading weights:   0%|          | 0/398 [00:00<?, ?it/s]

In [17]:
def text_sentiment(text):
    result = text_model(text[:512])[0]
    label = 1 if result['label'] == "POSITIVE" else 0
    return label, result['score']

In [18]:
def image_sentiment(row):
    path = os.path.join("dataset/memotion_dataset_7k/images", row['image_name'])
    
    image = Image.open(path).convert("RGB")
    
    inputs = clip_processor(
        text=labels,
        images=image,
        return_tensors="pt",
        padding=True
    )
    
    outputs = clip_model(**inputs)
    probs = outputs.logits_per_image.softmax(dim=1)
    
    idx = torch.argmax(probs).item()
    
    return idx, probs[0][idx].item()

In [19]:
def multimodal_sentiment(row):
    t_label, t_score = text_sentiment(row['text'])
    i_label, i_score = image_sentiment(row)
    
    # weighted fusion
    final_score = (t_label * t_score + i_label * i_score) / (t_score + i_score + 1e-6)
    
    final_label = "positive" if final_score >= 0.5 else "negative"
    
    return final_label

In [20]:
df = df.sample(50)

df["predicted"] = df.apply(multimodal_sentiment, axis=1)

In [21]:
def explain(row):
    text = row['text']
    pred = row['predicted']
    
    humour = str(row['humour']).lower()
    sarcasm = str(row['sarcasm']).lower()
    offensive = str(row['offensive']).lower()
    
    explanation = f"This meme is {pred} because "
    
    reasons = []
    
    # text-based reasoning
    if pred == "positive":
        if "funny" in humour:
            reasons.append("the text is humorous")
        if "not" in offensive:
            reasons.append("it is not offensive")
    
    else:
        if "sarcasm" in sarcasm:
            reasons.append("the text contains sarcasm")
        if "offensive" in offensive:
            reasons.append("it may be offensive")
    
    # image reasoning
    reasons.append("the image context supports this sentiment")
    
    return explanation + ", ".join(reasons) + "."

In [22]:
df_30 = df.head(30)

df_30["explanation"] = df_30.apply(explain, axis=1)

df_30[["image_name", "predicted", "explanation"]]

C:\Users\Palak Bhardwaj\AppData\Local\Temp\ipykernel_856\1468168292.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_30["explanation"] = df_30.apply(explain, axis=1)

,image_name,predicted,explanation
13,image_6443.jpg,negative,This meme is negative because it may be offens...
96,image_3814.jpg,negative,This meme is negative because it may be offens...
51,image_1088.png,negative,This meme is negative because it may be offens...
83,image_4210.jpg,positive,This meme is positive because the text is humo...
65,image_5991.jpg,negative,This meme is negative because the image contex...
32,image_4699.jpg,negative,This meme is negative because the image contex...
33,image_2352.jpg,negative,This meme is negative because it may be offens...
30,image_4141.png,positive,This meme is positive because the text is humo...
75,image_2517.jpeg,negative,This meme is negative because the image contex...
15,image_1421.jpg,positive,This meme is positive because the text is humo...
37,image_6121.jpg,negative,This meme is negative because the image contex...
70,image_2670.jpg,negative,This meme is negative because it may be offens...
63,image_1759.jpg,negative,This meme is negative because it may be offens...
69,image_51.jpg,positive,This meme is positive because the text is humo...
39,image_38.jpg,negative,This meme is negative because it may be offens...
50,image_4123.jpg,negative,This meme is negative because the image contex...
11,image_3384.jpg,negative,This meme is negative because the image contex...
34,image_246.png,positive,This meme is positive because the text is humo...
98,image_2115.png,negative,This meme is negative because it may be offens...
16,image_5091.jpg,negative,This meme is negative because it may be offens...
91,image_3539.jpg,negative,This meme is negative because it may be offens...
27,image_6705.png,negative,This meme is negative because it may be offens...
85,image_593.jpg,negative,This meme is negative because the image contex...
74,image_4014.jpg,negative,This meme is negative because the image contex...
2,image_5060.jpg,negative,This meme is negative because it may be offens...
28,image_6101.png,negative,This meme is negative because the image contex...
81,image_1913.jpg,negative,This meme is negative because it may be offens...
90,image_6479.jpg,negative,This meme is negative because the image contex...
61,image_4582.jpg,negative,This meme is negative because it may be offens...
56,image_5428.jpg,positive,This meme is positive because the text is humo...

In [24]:
!pip install sentence-transformers

Collecting sentence-transformers
  Downloading sentence_transformers-5.4.1-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from sentence-transformers) (5.7.0)
Requirement already satisfied: huggingface-hub>=0.23.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from sentence-transformers) (1.13.0)
Requirement already satisfied: torch>=1.11.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from sentence-transformers) (2.10.0)
Requirement already satisfied: numpy>=1.20.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from sentence-transformers) (2.1.3)
Requirement already satisfied: scikit-learn>=0.22.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from sentence-transformers) (1.15.3)
Requirement already satisfied: typing_extensions>=4.5.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from sentence-transformers) (4.12.2)
Requirement already satisfied: tqdm>=4.0.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from sentence-transformers) (4.67.1)
Requirement already satisfied: packaging>=20.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (6.0.2)
Requirement already satisfied: regex>=2025.10.22 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2026.4.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: typer in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.9.0)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: filelock>=3.10.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.17.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.3.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: anyio in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.7.0)
Requirement already satisfied: certifi in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2025.4.26)
Requirement already satisfied: httpcore==1.* in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.7)
Requirement already satisfied: h11>=0.16 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: joblib>=1.2.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.5.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from torch>=1.11.0->sentence-transformers) (1.13.3)
Requirement already satisfied: networkx>=2.5.1 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.4.2)
Requirement already satisfied: jinja2 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: setuptools in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from torch>=1.11.0->sentence-transformers) (72.1.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: colorama in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from tqdm>=4.0.0->sentence-transformers) (0.4.6)
Requirement already satisfied: sniffio>=1.1 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.2)
Requirement already satisfied: click<9.0.0,>=7.1.1 in c:\users\palak bhardwaj\anaconda3\lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (8.1.8)
Downloading sentence_transformers-5.4.1-py3-none-any.whl (571 kB)
   ---------------------------------------- 0.0/571.3 kB ? eta -:--:--
   ------------------ --------------------- 262.1/571.3 kB ? eta -:--:--
   ---------------------------------------- 571.3/571.3 kB 1.3 MB/s eta 0:00:00
Installing collected packages: sentence-transformers
Successfully installed sentence-transformers-5.4.1

In [25]:
from sentence_transformers import SentenceTransformer, util

# load lightweight BERT model
bert_model = SentenceTransformer('all-MiniLM-L6-v2')

def semantic_similarity(row):
    text = row['text']
    explanation = row['explanation']
    
    emb1 = bert_model.encode(text, convert_to_tensor=True)
    emb2 = bert_model.encode(explanation, convert_to_tensor=True)
    
    score = util.cos_sim(emb1, emb2).item()
    
    return score

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

C:\Users\Palak Bhardwaj\anaconda3\Lib\site-packages\huggingface_hub\file_download.py:138: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Palak Bhardwaj\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [26]:
from sentence_transformers import SentenceTransformer, util

bert_model = SentenceTransformer('all-MiniLM-L6-v2')

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

In [28]:
from sentence_transformers import util

def semantic_similarity(row):
    text = row['text']
    explanation = row['explanation']
    
    emb1 = bert_model.encode(text, convert_to_tensor=True)
    emb2 = bert_model.encode(explanation, convert_to_tensor=True)
    
    score = util.cos_sim(emb1, emb2).item()
    
    return score

In [29]:
df_30["semantic_score"] = df_30.apply(semantic_similarity, axis=1)

C:\Users\Palak Bhardwaj\AppData\Local\Temp\ipykernel_856\2685881191.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_30["semantic_score"] = df_30.apply(semantic_similarity, axis=1)

In [30]:
print("Average Semantic Similarity:", df_30["semantic_score"].mean())

Average Semantic Similarity: 0.13547884716341893

In [ ]:
from transformers import pipeline

nli_model = pipeline("text-classification", model="facebook/bart-large-mnli")

def nli_score(row):
    text = row['text']
    explanation = row['explanation']
    
    result = nli_model(f"{text} </s> {explanation}")[0]
    
    return result['score'] if result['label']=="ENTAILMENT" else 0

config.json: 0.00B [00:00, ?B/s]

C:\Users\Palak Bhardwaj\anaconda3\Lib\site-packages\huggingface_hub\file_download.py:138: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Palak Bhardwaj\.cache\huggingface\hub\models--facebook--bart-large-mnli. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

In [34]:
df_30["nli_score"] = df_30.apply(nli_score, axis=1)

C:\Users\Palak Bhardwaj\AppData\Local\Temp\ipykernel_856\4004720619.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_30["nli_score"] = df_30.apply(nli_score, axis=1)

In [35]:
print("Semantic:", df_30["semantic_score"].mean())
print("NLI:", df_30["nli_score"].mean())

Semantic: 0.13547884716341893
NLI: 0.0

In [36]:
def explain(row):
    text = str(row['text'])
    pred = row['predicted']
    
    explanation = f"The meme says: '{text[:50]}'. "
    
    if pred == "positive":
        explanation += "This is positive because the text expresses a light, humorous or enjoyable idea."
    else:
        explanation += "This is negative because the text expresses sarcasm, criticism, or a negative tone."
    
    return explanation

In [37]:
df_30["explanation"] = df_30.apply(explain, axis=1)

df_30["semantic_score"] = df_30.apply(semantic_similarity, axis=1)
df_30["nli_score"] = df_30.apply(nli_score, axis=1)

print("Semantic:", df_30["semantic_score"].mean())
print("NLI:", df_30["nli_score"].mean())

C:\Users\Palak Bhardwaj\AppData\Local\Temp\ipykernel_856\1444622034.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_30["explanation"] = df_30.apply(explain, axis=1)
C:\Users\Palak Bhardwaj\AppData\Local\Temp\ipykernel_856\1444622034.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_30["semantic_score"] = df_30.apply(semantic_similarity, axis=1)

Semantic: 0.5889249920845032
NLI: 0.0

C:\Users\Palak Bhardwaj\AppData\Local\Temp\ipykernel_856\1444622034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_30["nli_score"] = df_30.apply(nli_score, axis=1)